export const LOAD_RESOURCE = 'loadResource'
export const SAVE_RESOURCE = 'saveResource'
export const PUBLISH_RESOURCE = 'publishResource'
export const ADD_RESOURCE = 'addResource'
export const ADD_RESOURCE_TYPE = 'addType'
export const REMOVE_RESOURCE_TYPE = 'removeType'
export const SAVE_SETTINGS = 'saveSettings'
